=== inexas/fsm/com.inexas.fsm/data/fsm-V0.1.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
	Notes
	terminal-actions:
		If terminal-actions is set to TRUE then INITIAL and FINAL
		are allowed to have exit and entry actions respectively.
-->
<!ELEMENT fsm (
		initial-state,
		entry-action*,
		(activity-state|composite-state|decision|signal|state|synch-bar)*,
		exit-action*,
		final-state?) >
	<!ATTLIST fsm
		name CDATA #REQUIRED
		logger-name CDATA #IMPLIED
		logger-level (TRACE|DEBUG|INFO|WARN|ERROR|FATAL|OFF) "OFF"
		implementation CDATA #IMPLIED
		terminal-actions (TRUE|FALSE) "FALSE"
	>

<!-- vertices -->

<!ELEMENT composite-state (
		initial-state?,
		entry-action*,
		(activity-state|composite-state|decision|signal|state|synch-bar)*,
		(transition|reaction)*,
		exit-action*) >
	<!ATTLIST composite-state
		name CDATA #REQUIRED
		history (none|shallow|deep) "none">

<!-- The initial state has exactly one transition for
	which event will default to "Start" composite states
	have zero or one initial-states, FSMs have exactly one-->
<!ELEMENT initial-state (transition,exit-action*)>

<!-- The FSM can have zero or one final states. Only
	incoming transitions are allowed. The inclusion of
	entry actions is a probable departure from the 
	specification so this can be disabled in the FSM.
	Entry actions are really useful to clean up. -->
<!ELEMENT final-state (entry-action*)>

<!ELEMENT state (entry-action*,(transition|reaction)*,exit-action*)>
	<!ATTLIST state
		name CDATA #REQUIRED>

<!ELEMENT activity-state (entry-action*,transition,exit-action*)>
	<!ATTLIST activity-state
		name CDATA #REQUIRED>

<!ELEMENT decision (case*,default?)>
	<!ATTLIST decision
		name CDATA #REQUIRED
		query CDATA #REQUIRED>

<!ELEMENT case (transition)>
	<!ATTLIST case
		name CDATA #REQUIRED>

<!ELEMENT default (transition)>

<!ELEMENT synch-bar (entry-action*,transition*,exit-action*)>
	<!ATTLIST synch-bar
		name CDATA #REQUIRED>

<!ELEMENT signal (entry-action*,transition?,exit-action*)>
	<!ATTLIST signal
		name CDATA #REQUIRED>

<!ELEMENT entry-action (argument*)>
	<!ATTLIST entry-action
		name CDATA #REQUIRED>

<!ELEMENT exit-action (argument*)>
	<!ATTLIST exit-action
		name CDATA #REQUIRED>

<!-- transition and reaction support -->

<!--A transition may have zero or one events. Zero event transitions
	are OK for the starting transition, transitions from synchs, transitions
	from decisions.
	
	The name of the transition is optional, if not provided the 
	transition is automatically named "sourceStateName-eventName-targetStateName".
	The name must be unique for the whole model.
	
	If the transition contains more than one event name, several transitions are
	automatically created using the automatic name in which case the name 
	*must* be automatic.
	
	If there is no event the automatic name is "sourceStateName-targetStateName"
-->
<!ELEMENT transition (transition-action*)>
	<!ATTLIST transition
		name CDATA #IMPLIED
		target CDATA #REQUIRED
		event CDATA #IMPLIED
		guard CDATA #IMPLIED>

<!ELEMENT transition-action (argument*)>
	<!ATTLIST transition-action
		name CDATA #REQUIRED>

<!-- Think about whether event should be required for reactions given
	that the default name is XXX-event-XXX-->
<!ELEMENT reaction (reaction-action*)>
	<!ATTLIST reaction
		name CDATA #IMPLIED
		event CDATA #IMPLIED
		guard CDATA #IMPLIED>

<!ELEMENT reaction-action (argument*)>
	<!ATTLIST reaction-action
		name CDATA #REQUIRED>

<!--Arguments are provided in several data types according to the
	type attribute:
	
		Type		Value string will be interpreted as...
		####		#############################################
		parameter	parameter passed on handle event call, any type (should have class)
		call		a getter from implementation, e.g. "getTime" or "isBig"
		integer    	an integer value, e.g. "12321"
		string    	text, e.g. "This is some text"
		boolean 	boolean, must be either "true" or "false")
	
	For call arguments, the type for the argument is derived from
	the getter (getTime(), isActive()).
	
	You can provide other data types through the call type -->
<!ELEMENT argument EMPTY>
	<!ATTLIST argument
		type (parameter|call|integer|string|bool) "string"
		class CDATA #IMPLIED
		value CDATA #REQUIRED>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/smorgasbord.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!-- Smorgasbord: one of everything, this file is used for build
	 testing -->

<!--
<!ELEMENT fsm (
		initial-state,
		entry-action*,
		(activity-state|composite-state|decision|signal|state|synch-bar)*,
		exit-action*,
		final-state?) >
	<!ATTLIST fsm
		name CDATA #REQUIRED
		implementation CDATA #IMPLIED> -->
<fsm name="smorgasbord" implementation="com.inexas.fsm.Smorgasbord">

	<initial-state>
		<transition target="a" name="to-a" event="Start"/>
	</initial-state>
	
	<!--
	<!ELEMENT entry-action EMPTY>
		<!ATTLIST entry-action
			name CDATA #REQUIRED>
	-->
	<entry-action name="enter"/>
	<entry-action name="enter"/>
	
	<!--
	<!ELEMENT activity (entry-action*,transition*,exit-action*)>
		<!ATTLIST activity
			name CDATA #REQUIRED>
	-->	
	<activity-state name="a">
		<entry-action name="enter">
			<argument value="a1"/>
			<argument type="call" value="getA2"/>
			<argument type="integer" value="3"/>
			<argument type="string" value="a4"/>
			<argument type="bool" value="false"/>
		</entry-action>
		<entry-action name="enter"/>
		<transition name="to-cs-a1" target="cs-a" event="cs-a"/>
	</activity-state>
	<composite-state name="cs-a">
		<initial-state>
			<transition target="s" name="to-s" event="to-s"/>
		</initial-state>
		<state name="s">
			<transition target="a" name="to-a" event="to-a"/>
		</state>
		<activity-state name="a">
			<transition name="to-cs-a-s" target="s" event="to-cs-a-s"/>
			<exit-action name="exit"/>
			<exit-action name="exit"/>
		</activity-state>
		<transition target="cs" name="to-cs1" event="to-cs"/>
	</composite-state>
	
	<!--
	<!ELEMENT composite-state (
			initial-state,
			entry-action*,
			(activity|composite-state|decision|signal|state|synch-bar)*,
			transition*,
			exit-action*) >
		<!ATTLIST composite-state
			name CDATA #REQUIRED
			history (none|shallow|deep) "none">
	-->
	<composite-state name="cs" history="shallow">
		<initial-state>
			<transition target="a" name="to-a" event="to-a"/>
		</initial-state>
		<entry-action name="enter"/>
		<entry-action name="enter"/>
		<activity-state name="a">
			<entry-action name="enter"/>
			<transition target="cs" name="to-cs2" event="to-cs2"/>
		</activity-state>
		<composite-state name="cs">
			<initial-state>
				<transition target="s1" name="to-s1" event="to-s1"/>
			</initial-state>
			<state name="s1"/>
			<transition target="d0" name="to-d0" event="to-d0"/>
		</composite-state>
		<decision name="d0" query="query">
			<case name="d0">
				<transition target="signal" name="to-signal"/>
			</case>
		</decision>
		<signal name="signal">
			<transition target="s1" name="to-s1" event="to-s1"/>
		</signal>
		<state name="s1">
			<transition target="sb" name="to-sb"/>
		</state>
		<synch-bar name="sb">
			<transition target="endstate" name="to-endstate"/>
		</synch-bar>
		<state name="endstate"/>
		<transition target="cs-cs" name="to-cs-cs" event="to-cs-cs"/>
		<transition target="signal" name="to-signal" event="to-signal"/>
		<exit-action name="exit"/>
		<exit-action name="exit"/>
	</composite-state>
	<composite-state name="cs-cs">
		<initial-state>
			<transition target="cs1" name="to-cs1" event="to-cs1"/>
		</initial-state>
		<composite-state name="cs1">
			<initial-state>
				<transition target="s1" name="to-s1" event="to-s1"/>
			</initial-state>
			<state name="s1"/>
			<transition target="cs2" name="to-cs3" event="to-cs2"/>
		</composite-state>
		<composite-state name="cs2">
			<initial-state>
				<transition target="s1" name="to-s1" event="to-s1"/>
			</initial-state>
			<state name="s1"/>
		</composite-state>
		<transition target="d1" name="to-d1" event="to-d1"/>
		<transition target="/cs/H" name="to-cs-H" event="to-cs/H"/>
	</composite-state>

	<decision name="d1" query="query">
		<case name="c1">
			<transition name="to-a-c1" target="a"/>
		</case>
		<case name="c2">
			<transition name="to-a-c2" target="a"/>
		</case>
		<default>
			<transition name="to-a-default" target="cs-d"/>
			<!-- transition name="to-a-default" target="cs-d" event="to-a-default"/-->
		</default>
	</decision>
	<composite-state name="cs-d">
		<initial-state>
			<transition target="d2" name="to-d2" event="to-d2"/>
		</initial-state>
		<decision name="d2" query="query">
			<case name="c1">
				<!-- transition name="to-s1" target="s1" event="to-s1"/ -->
				<transition name="to-s1" target="s1"/>
			</case>
		</decision>
		<state name="s1"/>
		<transition target="signal" name="to-signal" event="to-signal"/>
	</composite-state>

	<!--
	<!ELEMENT signal (entry-action*,transition?,exit-action*)>
		<!ATTLIST signal
			name CDATA #REQUIRED
			is-start (true|false) "false"
			is-end (true|false) "false">
	-->
	<signal name="signal">
		<entry-action name="enter"/>
		<entry-action name="enter"/>
		<transition target="cs-signal" name="to-cs-signal" event="to-cs-signal"/>
		<exit-action name="exit"/>
		<exit-action name="exit"/>
	</signal>
	<composite-state name="cs-signal">
		<initial-state>
			<transition target="signal" name="to-signal" event="to-signal"/>
		</initial-state>
		<signal name="signal"/>
		<transition target="s1" name="to-s1" event="to-s1"/>
	</composite-state>
		
	<!--
	<!ELEMENT state (entry-action*,transition*,exit-action*)>
		<!ATTLIST state
			name CDATA #REQUIRED
			is-start (true|false) "false"
			is-end (true|false) "false">
	-->
	<state name="s1">
		<entry-action name="enter"/>
		<entry-action name="enter"/>
		<!--
		<!ELEMENT transition (event*,transition-action*)>
			<!ATTLIST transition
				name CDATA #REQUIRED
				target CDATA #REQUIRED
				guard CDATA #IMPLIED>
		-->
		<transition name="toCs" target="cs" guard="guard" event="s1,t->s2,e1">
			<!--
			<!ELEMENT transition-action EMPTY>
				<!ATTLIST transition-action
					name CDATA #REQUIRED>
			-->
			<transition-action name="transitOne" />
			<transition-action name="transitTwo" />
		</transition>
		<transition name="to-cs-state" target="cs-state" event="to-cs-state"/>
		<exit-action name="exit"/>
		<exit-action name="exit"/>
	</state>
	<composite-state name="cs-state">
		<initial-state>
			<transition target="s1" name="to-s1" event="to-s1"/>
		</initial-state>
		<state name="s1"/>
		<transition target="sb-1" name="to-sb-1" event="to-sb-1"/>
	</composite-state>

	<!--
	<!ELEMENT synch-bar (entry-action*,transition*,exit-action*)>
		<!ATTLIST synch-bar
			name CDATA #REQUIRED
			is-start (true|false) "false"
			is-end (true|false) "false">
	-->
	<composite-state name="sb-1">
		<initial-state>
			<transition target="s0" name="to-s0" event="to-s0"/>
		</initial-state>
		<state name="s0">
			<transition target="start-sb" name="to-start-sb"/>
		</state>
		<synch-bar name="start-sb">
			<entry-action name="enter"/>
			<entry-action name="enter"/>
			<transition target="s1" name="to-s1"/>
			<transition target="s2" name="to-s2"/>
			<exit-action name="exit"/>
			<exit-action name="exit"/>
		</synch-bar>
		<state name="s1">
			<transition target="end-sb" name="to-end-sb1"/>
		</state>
		<state name="s2">
			<transition target="end-sb" name="to-end-sb2"/>
		</state>
		<synch-bar name="end-sb">
			<transition target="done"/>
		</synch-bar>
		<state name="done"/>
		<transition target="cs" name="to-cs4" event="to-cs4"/>
	</composite-state>
	
	<!--
	<!ELEMENT exit-action EMPTY>
		<!ATTLIST transition-action
			name CDATA #REQUIRED>
	-->
	<exit-action name="exit"/>
	<exit-action name="exit"/>
	
	<final-state/>
</fsm>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/reaction.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!-- reaction: test the reactions -->
<fsm name="reaction" implementation="com.inexas.fsm.TestImplementation">
	<initial-state>
		<transition target="s0" event="*_Start"/>
	</initial-state>
	<state name="s0">
		<entry-action name="entryAction"/>
		<transition target="_SELF" event="transition">
			<transition-action name="transition"/>
		</transition>
		<reaction event="reaction">
			<reaction-action name="reaction"/>
		</reaction>
		<exit-action name="exitAction"/>
	</state>
</fsm>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/toaster.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!--
	This is a representation of the turnstyle FSM in the 
	Martin-FSM_Tutorial.pdf in /docs in this project
-->
<fsm name="toaster" implementation="com.inexas.fsm.Toaster">
	<!-- Missing from this diagram:
		 - dotted line twixt CheckTempterature and ReadColorSensor
		 - bug in diagram: Done event must swith heater off
		 - Martin uses activity shapes to join threads before the synch but
		   should use states
		-->
	<initial-state>
		<transition target="Idle" name="to-Idle" event="to-Idle"/>
	</initial-state>
	
	<state name="Idle">
		<transition target="WaitForStart" name="Start" event="Start"/>
	</state>
	
	<state name="WaitForStart">
		<!-- see the PDF for notes about this, it's here to force the start
			 synch to wait for the start event -->
		<transition target="ToastSynch" name="to-ToastSynch"/>
	</state>
	
	<synch-bar name="ToastSynch">
		<transition target="WaitingToCheckColor" name="to-WaitingToCheckColor"/>
		<transition target="HeaterControl" name="to-HeaterControl"/>
		<transition target="TimerRunning" name="to-TimerRunning">
			<transition-action name="resetTimer"/>
		</transition>
	</synch-bar>
	
	<state name="WaitingToCheckColor">
		<transition target="ReadColorSensor" name="Check" event="Check"/>
		<transition target="CheckColorDone" name="Done" event="Done"/>
	</state>
	<state name="CheckColorDone">
		<!-- added to diagram: wait for synch -->
		<transition target="EndToastSynch" name="to-EndToastSynch"/>
	</state>
	
	<activity-state name="ReadColorSensor">
		<entry-action name="readColorSensor"/>
		<transition target="ReadColorSynchWait" name="to-ReadColorSynchWait"/>
	</activity-state>
	
	<state name="ReadColorSynchWait">
		<!-- added to diagram: wait for synch -->
		<transition target="ReadColorSynch" name="to-ReadColorSynch"/>
	</state>
	
	<synch-bar name="ReadColorSynch">
		<transition target="s1" name="to-s1"/>
		<transition target="s2" name="to-s2"/>
	</synch-bar>

	<!-- added to diagram... -->
	<state name="s1">
		<transition target="CheckAbsoluteColor" name="to-CheckAbsoluteColor" event="s1"/>
	</state>
	<state name="s2">
		<transition target="CheckColorChangeRate" name="to-CheckColorChangeRate" event="s2"/>
	</state>
	
		
	<activity-state name="CheckAbsoluteColor">
		<entry-action name="checkAbsoluteColor"/>
		<transition target="SwitchAbsoluteColor" name="to-SwitchAbsoluteColor" event="to-SwitchAbsoluteColor"/>
	</activity-state>
	<decision name="SwitchAbsoluteColor" query="getAbsoluteColor">
		<case name="TooDark">
			<transition target="EndReadColorSynchWait" name="FireDone">
				<transition-action name="fireDone"/>
			</transition>
		</case>
		<default>
			<!-- this includes "just right" and "too dark" -->
			<transition target="EndReadColorSynchWait" guard="notTooLight" name="to-EndReadColorSynch"/>
		</default>
	</decision>

	<activity-state name="CheckColorChangeRate">
		<entry-action name="checkColorChangeRate"/>
		<transition target="SwitchColorChangeRate" name="to-SwitchColorChangeRate" event="to-SwitchColorChangeRate"/>
	</activity-state>
	<decision name="SwitchColorChangeRate" query="getSwitchColorChangeRate">
		<case name="Bad">
			<transition target="EndReadColorSynchWait" name="FireDone">
				<transition-action name="fireDone"/>
			</transition>
		</case>
		<default>
			<transition target="EndReadColorSynchWait"/>
		</default>
	</decision>
	
	<state name="EndReadColorSynchWait">
		<transition target="EndReadColorSynch" name="to-EndReadColorSynch"/>
	</state>
			
	<synch-bar name="EndReadColorSynch">
		<transition target="WaitingToCheckColor" name="WaitingToCheckColor"/>
	</synch-bar>

	<composite-state name="HeaterControl">
		<!-- unnamed in the PDF -->
		<initial-state>
			<transition target="HeaterOff" name="to-HeaterOff" event="to-HeaterOff"/>
		</initial-state>
		<state name="HeaterOff">
			<entry-action name="heaterOff"/>
			<transition target="CheckTemperature" name="Check" event="Check"/>
		</state>
		<activity-state name="CheckTemperature">
			<!--we require at least one action-->
			<entry-action name="checkTemperature"/>
			<transition target="Temperature" name="to-Temperature" event="to-Temperature"/>
		</activity-state>
		<decision name="Temperature" query="getTemperature">
			<case name="TooHot">
				<transition target="HeaterOff" name="to-HeaterOff"/>
			</case>
			<default>
				<transition target="HeaterOn" name="to-HeaterOn"/>
			</default>
		</decision>
		<state name="HeaterOn">
			<entry-action name="heaterOn"/>
			<transition target="CheckTemperature" name="Check" event="Check"/>
		</state>
		<transition target="HeaterControlDone" name="Done" event="Done">
			<!-- change from PDF - force heater off when done -->
			<transition-action name="heaterOff"/>
		</transition>
	</composite-state>
	<state name="HeaterControlDone">
		<!-- added to diagram: wait for synch -->
		<transition target="EndToastSynch" name="to-EndToastSynch"/>
	</state>
	
	<state name="TimerRunning">
		<transition target="TimerOff" name="Expired" event="Expired">
			<transition-action name="fireDone"/>
		</transition>
		<transition target="TimerOff" name="Done" event="Done">
			<transition-action name="stopTimer"/>
		</transition>
	</state>
	<state name="TimerOff">
		<!-- anonymous state below TimerRunning in PDF -->
		<transition target="EndToastSynch" name="to-EndToastSynch"/>
	</state>
	
	<synch-bar name="EndToastSynch">
		<!-- bottom of diagram in PDF -->
		<transition target="Idle" name="Eject">
			<transition-action name="eject"/>
		</transition>
	</synch-bar>
</fsm>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/turnstyle.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!--
	This is an implementation of the turnstyle FSM in the 
	Martin-FSM_Tutorial.pdf in /docs in this project
-->
<fsm name="turnstyle" implementation="com.inexas.fsm.Turnstyle">
	<!-- the initialize is missing from the diagram -->
	<initial-state>
		<transition target="NormalMode" name="to-NormalMode" event="to-NormalMode"/>
	</initial-state>
	<composite-state name="NormalMode" history="shallow">
		<initial-state>
			<transition target="Locked" name="to-Locked" event="to-Locked"/>
		</initial-state>
		<state name="Locked">
			<transition target="Unlocked" name="coin" event="coin">
				<transition-action name="unlock"/>
			</transition>
			<transition target="Violation" name="Pass" event="Pass">
				<transition-action name="alarm"/>
			</transition>
		</state>
		<state name="Unlocked">
			<transition target="Unlocked" name="Coin" event="Coin">
				<transition-action name="thankyou"/>
			</transition>
			<transition target="Locked" name="Pass" event="Pass">
				<transition-action name="lock"/>
				<transition-action name="thankyouOff"/>
			</transition>
		</state>
		<state name="Violation">
			<transition target="Locked" name="ready" event="ready">
				<transition-action name="resetAlarm"/>
				<transition-action name="lock"/>
			</transition>
			<transition target="Violation" name="Coin" event="Coin">
			</transition>
			<transition target="Violation" name="Pass" event="Pass"/>
			<transition target="Violation" name="Reset" event="Reset">
				<transition-action name="resetAlarm"/>
			</transition>
		</state>
		<transition target="DiagnosticMode" name="Diagnose" event="Diagnose">
			<transition-action name="saveDeviceStates"/>
			<!--
				Notes:
				1. The ThankyouOff action is moved from the initialize 
				transition in diagnostic mode as we don't support actions
				on the initial transition
				2. There should also be a lock action but it is
				not shown on the 
			-->
			<transition-action name="thankyouOff"/>
		</transition>
	</composite-state>
	
	<composite-state name="DiagnosticMode">
		<initial-state>
			<transition target="TestCoin" name="to-TestCoin" event="to-TestCoin"/>
		</initial-state>
		<state name="TestCoin">
			<transition target="TestPass" name="Coin" event="Coin">
				<transition-action name="thankyou"/>
			</transition>
		</state>
		<state name="TestPass">
			<transition target="TestCoin" name="Pass" event="Pass">
				<transition-action name="thankyouOff"/>
			</transition>
		</state>
		<transition target="DiagnosticMode" name="TestResetAlarm" event="TestResetAlarm">
			<transition-action name="resetAlarm"/>
		</transition>
		<transition target="DiagnosticMode" name="TestAlarm" event="TestAlarm">
			<transition-action name="alarm"/>
		</transition>
		<transition target="DiagnosticMode" name="TestUnlock" event="TestUnlock">
			<transition-action name="unlock"/>
		</transition>
		<transition target="DiagnosticMode" name="TestLock" event="TestLock">
			<transition-action name="lock"/>
		</transition>
		<!--diagram shows Reset going to /NormalMode/Locked this
			is invalid for us-->
		<transition target="NormalMode" name="Reset" event="Reset">
			<transition-action name="lock"/>
			<transition-action name="thankyouOff"/>
			<transition-action name="resetAlarm"/>
		</transition>
		<transition target="/NormalMode/H" name="Return" event="Return">
			<transition-action name="restoreDeviceStatus"/>
		</transition>
	</composite-state>
</fsm>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/actions.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!-- Test the actions -->
<fsm name="actions" implementation="com.inexas.fsm.Actions">
	<initial-state>
		<transition target="S1" event="Start">
			<transition-action name="toS1"/>
		</transition>
	</initial-state>
	
	<state name="S1">
		<entry-action name="entryAction1"/>
		<entry-action name="entryAction2"/>
		<transition target="_SELF" event="ToSelf">
			<transition-action name="toSelf1"/>
			<transition-action name="toSelf2">
				<argument value="a1"/>
				<argument type="parameter" value="p" class="java.lang.String"/>
				<argument type="call" value="getA2"/>
				<argument type="integer" value="3"/>
				<argument type="string" value="a4"/>
				<argument type="bool" value="false"/>
			</transition-action>
		</transition>
		<transition target="FINAL" event="toFinal" guard="toFinalGuard"/>
		<exit-action name="exitAction"/>
	</state>
	
	<final-state/>
</fsm>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/synch.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!-- This file is used for build testing -->

<fsm name="synch">

	<initial-state>
		<transition target="s0" name="Start" event="Start"/>
	</initial-state>
	
	<state name="s0">
		<transition target="s1" name="to-s1" event="to-s1"/>
	</state>
	
	<!-- when s1 is occupied the synch bar will fire -->
	<state name="s1">
		<transition target="start-sb" name="to-start-sb"/>
	</state>
	
	<!-- split into two threads -->
	<synch-bar name="start-sb">
		<transition target="s2" name="to-s2"/>
		<transition target="s3" name="to-s3"/>
	</synch-bar>
	
	<!-- This will be occupied by the synch -->
	<state name="s2">
		<transition target="end-sb" name="to-end-sb1"/>
	</state>
	
	<!-- so will this -->
	<state name="s3">
		<transition target="s4" name="to-s4" event="to-s4"/>
	</state>
	
	<state name="s4">
		<transition target="end-sb" name="to-end-sb2"/>
	</state>
	
	<!-- the end synch will wait for s4 to be occupied -->
	<synch-bar name="end-sb">
		<transition target="s5" name="to-s5"/>
	</synch-bar>

	<!-- this will terminate when entered -->
	<state name="s5"/>
</fsm>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/compstate.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!-- This is used for build testing composite states -->

<fsm name="compstate">
	<initial-state>
		<transition target="s0" name="to-s0" event="*_Start"/>
	</initial-state>

	<state name="s0">
		<transition target="cs" name="to-cs" event="to-cs"/>
		<transition target="cs/cs.s2" name="to-cs.s2" event="to-cs.s2"/>
		<transition target="cs/cs.cs/cs.cs.s2" name="to-cs.cs.s2" event="to-cs.cs.s2"/>
	</state>
	
	<composite-state name="cs">
		<initial-state>
			<transition target="cs.s1" name="to-cs.s1" event="to-cs.s1"/>
		</initial-state>
		
		<state name="cs.s1">
			<transition target="cs.s2" name="to-cs.s2" event="to-cs.s2"/>
		</state>
		
		<state name="cs.s2">
			<transition target="cs.cs" name="to-cs.cs" event="to-cs.cs"/>
			<transition target="/s0" name="to-s0" event="to-s0"/>
		</state>
		
		<composite-state name="cs.cs">
			<initial-state>
				<transition target="cs.cs.s1" name="to-cs.cs.s1" event="to-cs.cs.s1"/>
			</initial-state>
			
			<state name="cs.cs.s1">
				<transition target="cs.cs.s2" name="to-cs.cs.s2" event="to-cs.cs.s2"/>
			</state>
			
			<state name="cs.cs.s2"/>
			
			<transition target="cs.s1" name="to-cs.s1" event="to-cs.s1"/>
		</composite-state>
		
		<transition target="s0" name="to-s0" event="to-s0"/>
	</composite-state>
	
</fsm>

=== inexas/fsm/com.inexas.fsm/datatest/fsm/history.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fsm SYSTEM "../../data/fsm-V0.1.0.dtd">

<!-- This is used for build testing history -->

<fsm name="history">
	<initial-state>
		<transition target="shallow" name="to-shallow" event="to-shallow"/>
	</initial-state>
	
	<state name="s1">
		<transition target="shallow" name="to-shallow" event="to-shallow"/>
		<transition target="shallow/H" name="to-shallow-H" event="to-shallow/H"/>
		<transition target="s2" name="to-s2" event="to-s2"/>
	</state>
	
	<composite-state name="shallow" history="shallow">
		<initial-state>
			<transition target="shallow.s0" name="to-shallow.s0" event="to-shallow.s0"/>
		</initial-state>
		
		<state name="shallow.s0">
			<transition target="shallow.s1" name="to-shallow.s1" event="to-shallow.s1"/>
		</state>
		
		<state name="shallow.s1">
			<transition target="shallow.s0" name="to-shallow.s0" event="to-shallow.s0"/>
			<transition target="shallow.cs" name="to-shallow.cs" event="to-shallow.cs"/>
		</state>
		
		<composite-state name="shallow.cs">
			<!-- this should not maintain history -->
			<initial-state>
				<transition target="shallow.cs.s0" name="to-shallow.cs.s0" event="to-shallow.cs.s0"/>
			</initial-state>
			
			<state name="shallow.cs.s0">
				<transition target="shallow.cs.s1" name="to-shallow.cs.s1" event="to-shallow.cs.s1"/>
			</state>
			
			<state name="shallow.cs.s1">
				<transition target="shallow.cs.s0" name="to-shallow.cs.s0" event="to-shallow.cs.s0"/>
			</state>
			
			<transition target="/shallow/shallow.s1" name="to-shallow.s1" event="to-shallow.s1"/>
		</composite-state>
		
		<transition target="s1" name="to-s1" event="to-s1"/>
		<transition target="deep" name="to-deep" event="to-deep"/>
	</composite-state>
	
	<composite-state name="deep" history="deep">
		<initial-state>
			<transition target="deep.s0" name="to-deep.s0" event="to-deep.s0"/>
		</initial-state>
		
		<state name="deep.s0">
			<transition target="deep.cs" name="to-deep.cs" event="to-deep.cs"/>
		</state>
		
		<composite-state name="deep.cs">
			<!-- this should maintain history -->
			<initial-state>
				<transition target="deep.cs.s1" name="to-deep.cs.s1" event="to-deep.cs.s1"/>
			</initial-state>
			<state name="deep.cs.s1">
				<transition target="deep.cs.cs/deep.cs.cs.s0" name="to-deep.cs.cs.s0" event="to-deep.cs.cs.s0"/>
			</state>
			
			<composite-state name="deep.cs.cs">
				<!-- this should maintain history -->
				<state name="deep.cs.cs.s0">
					<transition target="deep.cs.cs.s1" name="to-deep.cs.cs.s1" event="to-deep.cs.cs.s1"/>
				</state>
				
				<state name="deep.cs.cs.s1">
					<transition target="deep.cs.cs.s0" name="to-deep.cs.cs.s0" event="to-deep.cs.cs.s0"/>
				</state>
				
				<transition target="deep.cs.s1" name="to-deep.cs.s1" event="to-deep.cs.s1"/>
			</composite-state>
			
			
			<transition target="deep.cs" name="to-deep.cs" event="to-deep.cs"/>
		</composite-state>
		
		<transition target="s2" name="to-s2" event="to-s2"/>
	</composite-state>
	
	<state name="s2">
		<transition target="deep" name="to-deep" event="to-deep"/>
		<transition target="deep/H*" name="to-deep-H*" event="to-deep/H*"/>
	</state>
</fsm>
